version: "3"

tasks:
  run-main:
    cmds:
      - go run src/main.go
  test:
    cmds:
      - go test -v ./src/...
  fmt:
    cmds:
      - gofmt -w -l ./src
  vet:
    cmds:
      - go vet ./src/...
  govulncheck:
    cmds:
      - govulncheck ./src/...
  up-latest:
    cmds:
      - go get -u ./src/...
      - go mod tidy
