version: "3"

tasks:
  run-main:
    cmds:
      - go run main.go
  test:
    cmds:
      - go test -v ./...
  fmt:
    cmds:
      - gofmt -w -l .
  vet:
    cmds:
      - go vet ./...
  govulncheck:
    cmds:
      - govulncheck ./...
