name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    permissions:
      contents: read # needed for actions/checkout
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: '${{ github.workspace }}/go.mod'
          cache: true

      - name: Install go-task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run fmt task
        run: diff -u <(echo -n) <(task fmt)

      - name: Run vet task
        run: task vet

      - name: Run govulncheck task
        run: task govulncheck

      - name: Run test
        run: task test
